### PR TITLE
Changed CWs on replies to be kept if content is sensitive OR if there is spoiler text

### LINKED ISSUE #1110: Phanpy discards Content Warning when replying to Private Mentions
### Site

phanpy.squirrel.rocks

### Version

2025.03.22.85d964f

### Instance

boosts.squirrel.pictures

### Browser

Firefox 136.0.4 on openSUSE Tumbleweed

### Bug description

When replying to a Private Mention that has a CW Phanpy defaults to CW disabled in the compose window, which means the reply would be sent without CW / the existing CW is discarded unless manually enabling CW again before sending.

### To reproduce

1. Receive a Private Mention with CW
2. Reply
3. In the Compose Window, note that the CW field is not displayed, the CW button shows CW disabled

### Expected behavior

The CW is kept intact by default.

### Other

_No response_

### PR DESCRIPTION
**Pull request by VirtualWolf**
This PR changes Phanpy's logic around whether the Content Warning field in the UI should be pre-filled with the CW from a toot you're replying to be _either_ if the `sensitive` flag is set _or_ if there is `spoiler_text` (a CW). This is to work around behaviour from clients like Tusky that set the `sensitive` flag back to false on replies with CWs when there isn't media attached.

Fixes #1110 (I described my investigation into this problem in that issue).

### CODE REVIEW

File: src/components/compose.jsx [hunk 1]
```diff
@@ -328,7 +328,7 @@ function Compose({
           prefs['posting:default:language']?.toLowerCase() ||
           DEFAULT_LANG,
       );
-      setSensitive(sensitive && !!spoilerText);
+      setSensitive(sensitive || spoilerText);
```
Comment (cheeaun) [inline src/components/compose.jsx:331]: I looked at this thoroughly.

It was initially just `sensitive` but changed to this `&&` check due to sensitive media, not CW https://github.com/cheeaun/phanpy/pull/261/commits/6540dd5642f03180df685bf8e4af188f8c35dc43

So, looking at the logic, seems like we only need to care about `spoilerText`, so this should work as the goal is to show CW field *if* there's spoiler text:

```
setSensitive(!!spoilerText);
```

Comment (VirtualWolf) [reply src/components/compose.jsx]: And changed.
